# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddCameraWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddCameraWidget(object):
    def setupUi(self, AddCameraWidget):
        AddCameraWidget.setObjectName("AddCameraWidget")
        AddCameraWidget.resize(410, 230)
        AddCameraWidget.setMinimumSize(QtCore.QSize(410, 230))
        AddCameraWidget.setMaximumSize(QtCore.QSize(410, 230))
        self.name = QtWidgets.QLabel(AddCameraWidget)
        self.name.setGeometry(QtCore.QRect(15, 80, 60, 20))
        self.name.setObjectName("name")
        self.nameEdit = QtWidgets.QLineEdit(AddCameraWidget)
        self.nameEdit.setGeometry(QtCore.QRect(90, 85, 290, 20))
        self.nameEdit.setObjectName("nameEdit")
        self.webCamera = QtWidgets.QRadioButton(AddCameraWidget)
        self.webCamera.setGeometry(QtCore.QRect(110, 10, 90, 20))
        self.webCamera.setObjectName("webCamera")
        self.link = QtWidgets.QLabel(AddCameraWidget)
        self.link.setGeometry(QtCore.QRect(15, 45, 60, 20))
        self.link.setObjectName("link")
        self.order = QtWidgets.QLabel(AddCameraWidget)
        self.order.setGeometry(QtCore.QRect(15, 115, 60, 20))
        self.order.setObjectName("order")
        self.orderBox = QtWidgets.QSpinBox(AddCameraWidget)
        self.orderBox.setGeometry(QtCore.QRect(90, 115, 90, 20))
        self.orderBox.setObjectName("orderBox")
        self.comment = QtWidgets.QLabel(AddCameraWidget)
        self.comment.setGeometry(QtCore.QRect(15, 150, 60, 20))
        self.comment.setObjectName("comment")
        self.cancelBtn = QtWidgets.QPushButton(AddCameraWidget)
        self.cancelBtn.setGeometry(QtCore.QRect(120, 190, 75, 25))
        self.cancelBtn.setObjectName("cancelBtn")
        self.comfirmBtn = QtWidgets.QPushButton(AddCameraWidget)
        self.comfirmBtn.setGeometry(QtCore.QRect(230, 190, 75, 25))
        self.comfirmBtn.setObjectName("comfirmBtn")
        self.commentEdit = QtWidgets.QLineEdit(AddCameraWidget)
        self.commentEdit.setGeometry(QtCore.QRect(90, 150, 290, 20))
        self.commentEdit.setObjectName("commentEdit")
        self.localCamera = QtWidgets.QRadioButton(AddCameraWidget)
        self.localCamera.setGeometry(QtCore.QRect(220, 10, 90, 20))
        self.localCamera.setObjectName("localCamera")
        self.typeLabel = QtWidgets.QLabel(AddCameraWidget)
        self.typeLabel.setGeometry(QtCore.QRect(15, 10, 60, 20))
        self.typeLabel.setObjectName("typeLabel")
        self.addressEdit = QtWidgets.QLineEdit(AddCameraWidget)
        self.addressEdit.setGeometry(QtCore.QRect(90, 45, 290, 20))
        self.addressEdit.setObjectName("addressEdit")

        self.retranslateUi(AddCameraWidget)
        QtCore.QMetaObject.connectSlotsByName(AddCameraWidget)

    def retranslateUi(self, AddCameraWidget):
        _translate = QtCore.QCoreApplication.translate
        AddCameraWidget.setWindowTitle(_translate("AddCameraWidget", "添加摄像头"))
        self.name.setText(_translate("AddCameraWidget", "  名    称"))
        self.webCamera.setText(_translate("AddCameraWidget", "网络摄像头"))
        self.link.setText(_translate("AddCameraWidget", "  视 频 源"))
        self.order.setText(_translate("AddCameraWidget", "  顺    序"))
        self.comment.setText(_translate("AddCameraWidget", "  备    注"))
        self.cancelBtn.setText(_translate("AddCameraWidget", "取  消"))
        self.comfirmBtn.setText(_translate("AddCameraWidget", "确  认"))
        self.localCamera.setText(_translate("AddCameraWidget", "本地摄像头"))
        self.typeLabel.setText(_translate("AddCameraWidget", "  类    型"))
