# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Connections.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Connections(object):
    def setupUi(self, Connections):
        Connections.setObjectName("Connections")
        Connections.resize(400, 360)
        Connections.setMinimumSize(QtCore.QSize(400, 360))
        Connections.setMaximumSize(QtCore.QSize(400, 360))
        self.addBtn = QtWidgets.QPushButton(Connections)
        self.addBtn.setGeometry(QtCore.QRect(130, 320, 75, 25))
        self.addBtn.setObjectName("addBtn")
        self.cancelBtn = QtWidgets.QPushButton(Connections)
        self.cancelBtn.setGeometry(QtCore.QRect(220, 320, 75, 25))
        self.cancelBtn.setObjectName("cancelBtn")
        self.comfirmBtn = QtWidgets.QPushButton(Connections)
        self.comfirmBtn.setGeometry(QtCore.QRect(310, 320, 75, 25))
        self.comfirmBtn.setObjectName("comfirmBtn")
        self.cameraLabel = QtWidgets.QLabel(Connections)
        self.cameraLabel.setGeometry(QtCore.QRect(39, 20, 50, 20))
        self.cameraLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.cameraLabel.setObjectName("cameraLabel")
        self.modelLabel = QtWidgets.QLabel(Connections)
        self.modelLabel.setGeometry(QtCore.QRect(179, 20, 50, 20))
        self.modelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.modelLabel.setObjectName("modelLabel")
        self.statusLabel = QtWidgets.QLabel(Connections)
        self.statusLabel.setGeometry(QtCore.QRect(330, 20, 50, 20))
        self.statusLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.statusLabel.setObjectName("statusLabel")

        self.retranslateUi(Connections)
        QtCore.QMetaObject.connectSlotsByName(Connections)

    def retranslateUi(self, Connections):
        _translate = QtCore.QCoreApplication.translate
        Connections.setWindowTitle(_translate("Connections", "匹配连接"))
        self.addBtn.setText(_translate("Connections", "添  加"))
        self.cancelBtn.setText(_translate("Connections", "取  消"))
        self.comfirmBtn.setText(_translate("Connections", "确  认"))
        self.cameraLabel.setText(_translate("Connections", "摄 像 头"))
        self.modelLabel.setText(_translate("Connections", "模型"))
        self.statusLabel.setText(_translate("Connections", "状态"))
