# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Connection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Connection(object):
    def setupUi(self, Connection):
        Connection.setObjectName("Connection")
        Connection.resize(356, 70)
        self.cameraBox = QtWidgets.QComboBox(Connection)
        self.cameraBox.setGeometry(QtCore.QRect(10, 10, 135, 22))
        self.cameraBox.setObjectName("cameraBox")
        self.modelBox = QtWidgets.QComboBox(Connection)
        self.modelBox.setGeometry(QtCore.QRect(160, 10, 130, 20))
        self.modelBox.setObjectName("modelBox")
        self.statusBox = QtWidgets.QCheckBox(Connection)
        self.statusBox.setGeometry(QtCore.QRect(310, 10, 30, 20))
        self.statusBox.setObjectName("statusBox")
        self.commentEdit = QtWidgets.QLineEdit(Connection)
        self.commentEdit.setGeometry(QtCore.QRect(10, 40, 330, 20))
        self.commentEdit.setObjectName("commentEdit")

        self.retranslateUi(Connection)
        QtCore.QMetaObject.connectSlotsByName(Connection)

    def retranslateUi(self, Connection):
        _translate = QtCore.QCoreApplication.translate
        self.statusBox.setText(_translate("Connection", "开"))
