# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


# 主界面
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # 父类QMianWindow对象的设置
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 600)
        MainWindow.setMinimumSize(QtCore.QSize(980, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/Nicola.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(24, 24))

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)  # 水平布局
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.cameraBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.cameraBox.sizePolicy().hasHeightForWidth())
        self.cameraBox.setSizePolicy(sizePolicy)
        self.cameraBox.setMinimumSize(QtCore.QSize(211, 0))
        self.cameraBox.setMaximumSize(QtCore.QSize(211, 16777215))
        self.cameraBox.setObjectName("cameraBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.cameraBox)
        self.verticalLayout.setContentsMargins(5, 2, 5, 5)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout.addWidget(self.cameraBox)

        self.videoBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.videoBox.sizePolicy().hasHeightForWidth())
        self.videoBox.setSizePolicy(sizePolicy)
        self.videoBox.setObjectName("videoBox")
        self.gridLayout = QtWidgets.QGridLayout(self.videoBox)
        self.gridLayout.setContentsMargins(5, 2, 5, 5)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout.addWidget(self.videoBox)

        self.infoBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.infoBox.sizePolicy().hasHeightForWidth())
        self.infoBox.setSizePolicy(sizePolicy)
        self.infoBox.setMinimumSize(QtCore.QSize(211, 0))
        self.infoBox.setMaximumSize(QtCore.QSize(211, 16777215))
        self.infoBox.setObjectName("infoBox")
        self.displayLabel = QtWidgets.QLabel(self.infoBox)
        self.displayLabel.setGeometry(QtCore.QRect(15, 60, 180, 120))
        self.displayLabel.setText("")
        self.displayLabel.setObjectName("displayLabel")
        self.commentLabel = QtWidgets.QLabel(self.infoBox)
        self.commentLabel.setGeometry(QtCore.QRect(15, 30, 100, 20))
        self.commentLabel.setText("")
        self.commentLabel.setObjectName("commentLabel")
        self.horizontalLayout.addWidget(self.infoBox)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout.setStretch(2, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 980, 22))
        self.menubar.setObjectName("menubar")
        self.setting = QtWidgets.QMenu(self.menubar)
        self.setting.setObjectName("setting")
        # self.tools = QtWidgets.QMenu(self.menubar)
        # self.tools.setObjectName("tools")
        # self.query = QtWidgets.QMenu(self.menubar)
        # self.query.setObjectName("query")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        #self.infractionQuery = QtWidgets.QAction(MainWindow)
        #self.infractionQuery.setObjectName("infractionQuery")

        # self.helmetQuery = QtWidgets.QAction(MainWindow)
        # self.helmetQuery.setObjectName("helmetQuery")
        # self.gloveQuery = QtWidgets.QAction(MainWindow)
        # self.gloveQuery.setObjectName("gloveQuery")
        # self.cloesQuery = QtWidgets.QAction(MainWindow)
        # self.cloesQuery.setObjectName("cloesQuery")
        # self.shoesQuery = QtWidgets.QAction(MainWindow)
        # self.shoesQuery.setObjectName("shoesQuery")
        # self.fallQuery = QtWidgets.QAction(MainWindow)
        # self.fallQuery.setObjectName("fallQuery")


        # self.addCamera = QtWidgets.QAction(MainWindow)
        # self.addCamera.setObjectName("addCamera")
        # self.addModel = QtWidgets.QAction(MainWindow)
        # self.addModel.setObjectName("addModel")
        # self.connection = QtWidgets.QAction(MainWindow)
        # self.connection.setObjectName("connection")
        # self.deleteResourse = QtWidgets.QAction(MainWindow)
        # self.deleteResourse.setObjectName("deleteResourse")
        # self.quit = QtWidgets.QAction(MainWindow)
        # self.quit.setObjectName("quit")
        self.setDistance = QtWidgets.QAction(MainWindow)
        self.setDistance.setObjectName("setDistance")


        # 设置的下拉动作栏
        # self.setting.addAction(self.addCamera)
        # self.setting.addAction(self.addModel)
        # self.setting.addAction(self.connection)
        # self.setting.addAction(self.deleteResourse)
        # self.setting.addAction(self.quit)
        self.setting.addAction(self.setDistance)

        # 查询的下拉动作栏
        # self.query.addAction(self.helmetQuery)
        # self.query.addAction(self.gloveQuery)
        # self.query.addAction(self.cloesQuery)
        # self.query.addAction(self.shoesQuery)
        # self.query.addAction(self.fallQuery)

        self.menubar.addAction(self.setting.menuAction())
        # self.menubar.addAction(self.query.menuAction())
        # self.menubar.addAction(self.tools.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "智能电力监督培训系统"))
        # MainWindow.setWindowTitle(_translate("MainWindow", "工地安全行为识别系统"))
        self.cameraBox.setTitle(_translate("MainWindow", " 摄 像 头 "))
        self.videoBox.setTitle(_translate("MainWindow", " 画 面 "))
        self.infoBox.setTitle(_translate("MainWindow", " 信 息 "))
        self.setting.setTitle(_translate("MainWindow", "设置"))
        # self.tools.setTitle(_translate("MainWindow", "工具"))
        #self.query.setTitle(_translate("MainWindow", "查询"))

        #self.infractionQuery.setText(_translate("MainWindow", "违规查询"))
        # self.helmetQuery.setText(_translate("MainWindow", "安全头盔违规"))
        # self.gloveQuery.setText(_translate("MainWindow", "安全手套违规"))
        # self.cloesQuery.setText(_translate("MainWindow", "安全服违规"))
        # self.shoesQuery.setText(_translate("MainWindow", "安全靴违规"))
        # self.fallQuery.setText(_translate("MainWindow", "摔倒情况"))
        #
        # self.addCamera.setText(_translate("MainWindow", "添加摄像头"))
        # self.addModel.setText(_translate("MainWindow", "添加模型"))
        # self.connection.setText(_translate("MainWindow", "匹配连接"))
        # self.deleteResourse.setText(_translate("MainWindow", "删除资源"))
        # self.quit.setText(_translate("MainWindow", "退出"))
        self.setDistance.setText(_translate("MainWindow", "设置距离"))
